### PR TITLE
Restructure main code

### PR DESCRIPTION
**Pull request by valentk777**
- restructure a code
- uncoupled main file to classes
- enums introduced
- close app issue fixed
- global path handling added
- navigation with ASDW added
- .gitignore updated
- requirements.txt file added

### CODE REVIEW

**Comment by Gooodgis** [comment]
Thanks for the PR! It's a really nice refactor.

That said, this seems like a larger pull request. While your code improves my "code smell" and other problems, I'm not ready for such a restructure in one fell swoop. I'd prefer smaller PRs to pick and choose what I think should be merged. 

### More thoughts:
- I really like the app closing fix, although it seems the close button is now broken on Linux.
- Fine with classes in their own .py
- I like the WASD addition 
- requirements.txt is fine

**Comment by valentk777** [comment]
thank you for your comment!

about the exit in Linux. maybe in Linux, they use exit-type commands (the ones I remove). so if we add them back, everything should be fine. sadly I am using a Windows machine and starting VM sounds like a bit of overkill for me :D .

making everything in more minor PR's. That's doable but takes the same amount of time I already invested. Is there something you do not like stopping you from merging PR? are added tests (never created test for a game, maybe it would be hard, but I can try) would increase your confidence?

On the other hand,  if I understand you correctly, you suggest closing this PR. Am I right?

I will leave my version on the forked version. in case of closing, you can always refer to that if you want to add smth you like.

**Comment by valentk777** [comment]
I think I fix the Linux closing app issue. could you test any time available? thanks!

**Comment by Gooodgis** [comment]
Linux closing works! Although if you're in game, clicking the close button goes to the menu. Clicking it again from the menu closes the app.

**Comment by Gooodgis** [comment]
1. The path handling has slightly convoluted running the project imo, especially for newbies. If we can make it easier to run the game, then I'm fine with keeping it.

I'd like to stick with something like...
```sh
python main.py
```
versus
```sh
python -m src.main
```
Maybe we could just update the readme.md to show how to play...

2. Can we incorporate the score saving system that was recently added in the base branch?

**Comment by valentk777** [comment]
1. If we remove the src folder and move everything to the base dir this will work the same way. We can do that for sure.
2. Score saving system is functionally the same as in the current master now (after pr you mention). There is an automatic file creation, and file update if the new score is bigger. In addition, in this PR, I avoid extensive path checking and text file usage instead of actual JSON as it should be based on the data type inside. I have deleted the actual file from git and added .gitignore in order to not commit someone's score accidentally. A file will be created for you when you start a game. So it should work the same as it was before but with additional features. If there is smth I missed in this functionality, I can update that part for sure :)

**Comment by valentk777** [comment]
I updated a code to be able to call `python main.py` from the main root. all features related to files and scores are already in PR. any more comments or suggestions? :)

**Comment by Gooodgis** [comment]
Nope. Great work!

Thanks for being flexible too :)

**Comment by valentk777** [comment]
Thanks for reviews and comments. Results in code, most of the time, achieved only finding consensus. And your comments were really good ones. So thanks for your feedback too! :)

**Pull request merged**
